services:
  database:
    image: mariadb:11
    container_name: projet-api-data-database
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u${MARIADB_USER} -p${MARIADB_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    container_name: projet-api-data-api
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

volumes:
  dbdata:
